version: '2'
services:
  backend:
    image: metrafonic/thehybridspace
    cpu_shares: 100
    mem_limit: 224288000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/thehybridspace
    ports:
      - 80:3000
    links:
      - db

  db:
    image: metrafonic/thehybridspace_db
    cpu_shares: 100
    mem_limit: 224288000
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres

