version: '2'
services:
  backend:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/thehybridspace
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: postgres
    environment:
    - DEBUG=false
    - DB_USER=postgres
    - DB_PASS=postgres
    volumes:
      - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/init.sql
