version: '2'
services:
  web:
    restart: always
    build: .
    cpu_shares: 100
    mem_limit: 224288000
    environment:
       DATABASE_URL: postgres://postgres:postgres@db:5432/thehybridspace
       ADMIN_USERNAME: admin
       ADMIN_PASSWORD: pass
    ports:
      - 80:3000
    links:
      - db

  db:
    restart: always
    build: ./Docker/hybridspace_db/
    cpu_shares: 100
    mem_limit: 224288000
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
